inherit_gem:
  govuk-lint: "configs/rubocop/all.yml"
AllCops:
  TargetRubyVersion: 2.6
Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - "spec/**/*.rb"
    - "config/routes.rb"
    - "config/environments/*.rb"

Rails/HelperInstanceVariable:
  Exclude:
    - "app/helpers/pagination_helper.rb"
